# Generated by Django 5.1.5 on 2025-01-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_groups.group')),
            ],
        ),
        migrations.DeleteModel(
            name='Mensages',
        ),
    ]
