# Generated by Django 5.1.5 on 2025-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_groups', '0002_mensage_delete_mensages'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
